#if !canImport(ObjectiveC)
import XCTest

extension ColorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColorTests = [
        ("testContrastRatio", testContrastRatio),
        ("testConvertToHSL", testConvertToHSL),
        ("testFromHex", testFromHex),
        ("testIsDark", testIsDark),
        ("testRelativeLuminance", testRelativeLuminance),
        ("testToHex", testToHex),
        ("testYIQ", testYIQ),
    ]
}

extension TemperatureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TemperatureTests = [
        ("testRGB", testRGB),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ColorTests.__allTests__ColorTests),
        testCase(TemperatureTests.__allTests__TemperatureTests),
    ]
}
#endif
